In [3]:
import numpy as np
import pandas as pd

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

# Inspection and Properties:

print(temperatures_w1.shape)
print(temperatures_w1.dtype)
print(temperatures_w1.size)
print(temperatures_w1.ndim)

# Array Operations: 

temperatures_Fahrenheit = (temperatures_w1 * 9/5) + 32 
print(temperatures_Fahrenheit)

print(temperatures_w1.max())
print(temperatures_w1.min())
print(temperatures_w1.mean())


# Array Slicing and Indexing: 
print(temperatures_w1[0:3])
print(temperatures_w1[-2:])
print(temperatures_w1[2:5])


# 5. Create a 2D Array: 

temperatures = np.array([
     [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
     [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
print(temperatures)

# Inspect and Slice the 2D Array: 

print(temperatures.shape)
print(temperatures.dtype)
print(temperatures.size)
print(temperatures.ndim)

print(temperatures[0])
print(temperatures[1])
print(temperatures[:, -2:])

In [ ]:
marks = pd.Series( [95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)


# Indexing and Slicing:

print(marks.iloc[0])
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])
print(marks.iloc[2])
print(marks[marks > 90])


marks.loc['Rank1']= 100
print(marks)

marks= marks.drop('Rank5')
print(marks)

cgpa = marks / 10
print(cgpa)

In [ ]:
transactions  = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics' ],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West','South', 'North' ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400 ]

}
transactions = pd.DataFrame(transactions)
print(transactions)

In [12]:
transactions.head(3)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300

In [11]:
transactions.tail(3)

   TransactionID ProductCategory Region  Amount
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [13]:
transactions.shape

(10, 4)

In [15]:
print(transactions.columns)
print(transactions.dtypes)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [19]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [21]:

print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [22]:
result = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(result)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [28]:
print(transactions['ProductCategory'].value_counts())
print(transactions['Region'].unique())
print(transactions['Region'].nunique())
print(transactions.groupby('Region')['Amount'].mean())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64
<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str
4
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [29]:
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [33]:
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [34]:
transactions = transactions.drop(
    transactions[transactions['TransactionID'] == 109].index
)

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [35]:
transactions = transactions.drop(columns=['Discount'])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400